version: '3.8'

services:
  calotracker:
    build: .
    image: yashtnaik/calotracker:latest
    ports:
      - "5000:5000"
    volumes:
      - calorie_data:/app/calories.db
    restart: unless-stopped

volumes:
  calorie_data:
