apiVersion: apps/v1
kind: Deployment
metadata:
  name: calotracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calotracker
  template:
    metadata:
      labels:
        app: calotracker
    spec:
      containers:
        - name: calotracker
          image: yashtnaik/calotracker:37fe03311a4b52cadee1324c08fcbc420f9c6544
          ports:
            - containerPort: 80

