apiVersion: apps/v1
kind: Deployment
metadata:
  name: calotracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calotracker
  template:
    metadata:
      labels:
        app: calotracker
    spec:
      containers:
        - name: calotracker
          image: yashtnaik/calotracker:3817230eecd68f040b127f84b52db9ffdd07446d
          ports:
            - containerPort: 80

