apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: calotracker:apps/Deployment:default/calotracker
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"calotracker:apps/Deployment:default/calotracker","deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-07-18T14:40:41Z","generation":1,"name":"calotracker","namespace":"default","resourceVersion":"9958","uid":"a9b325d6-9c14-4bfd-984f-bcc9c28e8f6b"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"calotracker"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"calotracker"}},"spec":{"containers":[{"image":"yashtnaik/calotracker:latest","imagePullPolicy":"Always","name":"calotracker","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2025-07-18T14:40:41Z","lastUpdateTime":"2025-07-18T14:40:59Z","message":"ReplicaSet \"calotracker-7cf47d774f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-07-19T09:31:18Z","lastUpdateTime":"2025-07-19T09:31:18Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2025-07-18T14:40:41Z"
  generation: 3
  name: calotracker
  namespace: default
  resourceVersion: "17257"
  uid: a9b325d6-9c14-4bfd-984f-bcc9c28e8f6b
spec:
  progressDeadlineSeconds: 600
  replicas: 3 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: calotracker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: calotracker
    spec:
      containers:
      - image: yashtnaik/calotracker:latest
        imagePullPolicy: Always
        name: calotracker
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-07-18T14:40:41Z"
    lastUpdateTime: "2025-07-18T14:40:59Z"
    message: ReplicaSet "calotracker-7cf47d774f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-19T10:42:57Z"
    lastUpdateTime: "2025-07-19T10:42:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
