name: Docker Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: yashtnaik/calotracker
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image with Compose
      run: |
        docker compose build
        docker tag yashtnaik/calotracker:latest ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
        docker rmi yashtnaik/calotracker

    - name: Push Docker Image
      run: |
        docker push ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

    - name: Update deployment.yaml
      env:
        GH_USERNAME: ${{ vars.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        sed -i "s|image: .*|image: ${DOCKER_IMAGE}:${IMAGE_TAG}|" manifest/deployment.yaml
        git config --global user.name "${GH_USERNAME}"
        git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
        git remote set-url origin https://${GH_USERNAME}:${GH_TOKEN}@github.com/yashtnaik/calotracker.git
        git add manifest/deployment.yaml
        git commit -m "Update image tag to ${IMAGE_TAG}"
        git push origin HEAD:main

