name: Build and Push Docker Image

on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '*/2 * * * *'
  push:
    branches:
      - main
env:
  IMAGE_NAME: Calotracker
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo 'docker login -u "${{ vars.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"'

      - name: Build Docker image
        run: echo 'docker build -t ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 1
    concurrency:
      group: production-deploy
      cancel-in-progress: false   #false will wait for the previous job to complete
    steps:
      - name: Push Docker image
        run: |
              echo 'docker push ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}'
              sleep 180
